{
    'name': 'filter aprl products',
    'version': '1.0.0',
    'category': 'Industries',
    'summary': """A complete APRL product Management System that cover all areas of 
     product services""" ,
    'description': """product software""",
    'author': 'FlowEazy Techno Solutions',
    'company': 'Floweazy Techno Solutions',
    'maintainer': 'Floweazy Techno Solutions',
    'website': 'https://www.odoo.com',
    'depends': ['product','sale'],
    'data': ['views/sub_categories.xml',
             'views/head_categories.xml'],
    'assets': {},
    'images': [],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
