
{
    'name': 'Flower Shop',
    'version': '1.0',
    'summary': 'FlowEazy Software Management',
    'sequence': -100,
    'description': """Flower Management Software""",
    'category': 'Productivity',
    'website': 'https://www.odoomates.tech',
    'license': 'LGPL-3',
    'depends': ['sale','product'],
    'data': ['views/classifiers.xml',
             'views/classifiers_main.xml',
             #'views/product_inherit.xml',
              ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
